import React, {useEffect,useRef,useState} from 'react';
import {BookOpen,Check,LoaderCircle,Play,Search,Trash2,X} from 'lucide-react';
import type {CommandResult,MemoryHit,Snapshot,SummonBridge} from './types';

type Props={snapshot:Snapshot;bridge:SummonBridge;receipt:CommandResult|null;onClose:()=>void;onSnapshot:(snapshot:Snapshot)=>void;onResult:(result:CommandResult)=>void};
export function KnowledgePanel({snapshot,bridge,receipt,onClose,onSnapshot,onResult}:Props){
  const dialog=useRef<HTMLDialogElement>(null);
  const [tab,setTab]=useState<'memory'|'routines'>(receipt?'routines':'memory');
  const [query,setQuery]=useState('');
  const [hits,setHits]=useState<MemoryHit[]|null>(null);
  const [text,setText]=useState('');
  const [projectId,setProjectId]=useState(snapshot.currentProjectId||'');
  const [name,setName]=useState('');
  const [trigger,setTrigger]=useState('');
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  const [notice,setNotice]=useState('');
  const [savedReceipt,setSavedReceipt]=useState('');
  const knowledge=snapshot.knowledge;
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;dialog.current?.showModal();return()=>previous?.focus();},[]);
  const act=async(task:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{await task();}catch(error){setError(error instanceof Error?error.message:String(error));}finally{setBusy(false);}};
  const workspace=(id:string|null)=>snapshot.projects.find(item=>item.id===id)?.name||'Across workspaces';
  const scope=<label className="settings-field">Remember for<select aria-label="Memory or routine workspace" value={projectId} onChange={event=>setProjectId(event.target.value)}><option value="">Across workspaces</option>{snapshot.projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label>;
  return <dialog ref={dialog} className="preferences-dialog knowledge-dialog" aria-labelledby="knowledge-title" onCancel={event=>{event.preventDefault();onClose();}} onClick={event=>{if(event.target===dialog.current)onClose();}}>
    <div className="preferences-content"><header className="preferences-heading"><div><span className="eyebrow">A MEMORY YOU CAN READ</span><h2 id="knowledge-title">Memory & routines</h2></div><button className="icon-button" aria-label="Close memory" onClick={onClose}><X size={20}/></button></header>
    <div className="knowledge-tabs" role="group" aria-label="Memory sections"><button aria-pressed={tab==='memory'} onClick={()=>setTab('memory')}>Saved facts & notes<span>{knowledge?.memories.length||0}</span></button><button aria-pressed={tab==='routines'} onClick={()=>setTab('routines')}>Routines<span>{knowledge?.routines.length||0}</span></button></div>
    <div className="preferences-scroll">
      {error&&<div className="preferences-error" role="alert">{error}</div>}
      {notice&&<p className="knowledge-notice" role="status"><Check size={14}/>{notice}</p>}
      {busy&&<p className="knowledge-notice" role="status"><LoaderCircle size={14} className="spinner"/>Working locally…</p>}
      {tab==='memory'?<>
        <section className="preference-section knowledge-search"><h3><Search size={16}/>Find the context</h3><p className="preference-note">Search facts you saved and short, sourced excerpts from Second Brain’s Home and project hubs. Your notes stay in place.</p><form onSubmit={event=>{event.preventDefault();void act(async()=>{setHits(await bridge.searchMemory(query,{limit:10}));});}}><label className="sr-only" htmlFor="memory-search">Search saved memory and project notes</label><input id="memory-search" value={query} maxLength={500} onChange={event=>setQuery(event.target.value)} placeholder="A project, a decision, a detail…"/><button className="button" disabled={busy||!query.trim()}><Search size={14}/>Search</button></form>
        {hits!==null&&<div className="knowledge-hits" aria-live="polite">{hits.length?hits.map(hit=><article className="memory-entry" key={hit.id}><div className="memory-provenance"><span>{hit.kind==='explicit'?'Saved fact':'Retrieved note'}</span><span>{workspace(hit.projectId)}</span></div><p>{hit.text}</p><small title={hit.source.path}>{hit.source.label}{hit.source.line?` · line ${hit.source.line}`:''}{hit.source.modifiedAt?` · updated ${new Date(hit.source.modifiedAt).toLocaleDateString()}`:''}</small></article>):<p className="knowledge-empty">No matching facts or project notes. Try a project name or a few specific words.</p>}</div>}
        <details className="knowledge-sources"><summary>{knowledge?.sources.length||0} project notes available</summary><p className="preference-note">Only Home.md and project hubs from your configured Second Brain workspace. Updated when searched.</p>{knowledge?.sources.map(item=><div key={item.id} title={item.path}>{item.title}</div>)}{!knowledge?.sources.length&&<p className="preference-note">Add your vault as a workspace named Second Brain to enable project-note search.</p>}{knowledge?.health.errors.map((message,index)=><p key={index} className="preferences-error">{message}</p>)}</details></section>
        <section className="preference-section"><h3><BookOpen size={16}/>Something to remember</h3><form className="knowledge-form" onSubmit={event=>{event.preventDefault();void act(async()=>{onSnapshot(await bridge.remember({text,projectId:projectId||null}));setText('');setHits(null);setNotice('Fact saved. Both connected agents can find it.');});}}><label className="settings-field">A fact you want to keep<textarea value={text} maxLength={2000} rows={3} onChange={event=>setText(event.target.value)} placeholder="For this project, the course workbook is the source of truth." required/></label>{scope}<button className="button primary" disabled={busy||!text.trim()}>Remember this</button></form></section>
        <section className="preference-section"><h3>Saved by you</h3>{knowledge?.memories.length?knowledge.memories.map(item=><article className="memory-entry" key={item.id}><div className="memory-provenance"><span>{workspace(item.projectId)}</span><button className="text-button" disabled={busy} aria-label={`Forget fact: ${item.text}`} onClick={()=>void act(async()=>{onSnapshot(await bridge.forget(item.id));setHits(null);setNotice('Fact removed.');})}><Trash2 size={13}/>Forget</button></div><p>{item.text}</p><small>{item.source} · {new Date(item.updatedAt).toLocaleDateString()}</small></article>):<p className="knowledge-empty">No saved facts yet. Summon keeps your explicit memories separate from observed activity and retrieved notes.</p>}</section>
      </>:<>
        <section className="preference-section"><h3>Commands worth keeping</h3><p className="preference-note">Run a familiar command successfully, then save it under a phrase you’ll remember. Type or say that exact phrase to use it again. Routines run without a model call.</p>
        {receipt?.routineReceiptId&&savedReceipt!==receipt.routineReceiptId?<form className="knowledge-form" onSubmit={event=>{event.preventDefault();void act(async()=>{onSnapshot(await bridge.saveRoutine({receiptId:receipt.routineReceiptId!,name,trigger,projectId:projectId||null}));setSavedReceipt(receipt.routineReceiptId!);setName('');setTrigger('');setNotice('Routine saved. Say or type its exact phrase to run it.');});}}><div className="routine-proof"><span><Check size={14}/>Command completed</span><p>{receipt.completedCommand}</p></div><label className="settings-field">Routine name<input value={name} maxLength={80} onChange={event=>setName(event.target.value)} placeholder="Morning desk" required/></label><label className="settings-field">The phrase you’ll use<input value={trigger} maxLength={120} onChange={event=>setTrigger(event.target.value)} placeholder="morning desk" required/><span>Choose a unique phrase that isn’t already a built-in command.</span></label>{scope}<button className="button primary" disabled={busy||!name.trim()||!trigger.trim()}>Save routine</button></form>:<p className="knowledge-empty">Use “Save as routine” after a successful command in the command bar.</p>}</section>
        <section className="preference-section"><h3>Your routines</h3>{knowledge?.routines.length?knowledge.routines.map(item=><article className="memory-entry routine-entry" key={item.id}><div className="memory-provenance"><strong>{item.name}</strong><span>{workspace(item.projectId)}</span></div><p>“{item.trigger}” <span aria-hidden="true">→</span> {item.command}</p><div className="routine-actions"><small>{item.useCount?`Used ${item.useCount} ${item.useCount===1?'time':'times'}`:'Ready to use'}</small><button className="button small-button" disabled={busy} onClick={()=>void act(async()=>{const result=await bridge.runRoutine(item.id);onSnapshot(await bridge.snapshot());onResult(result);onClose();})}><Play size={13}/>Run</button><button className="text-button" disabled={busy} aria-label={`Remove routine ${item.name}`} onClick={()=>void act(async()=>{onSnapshot(await bridge.removeRoutine(item.id));setNotice('Routine removed.');})}><Trash2 size={13}/>Remove</button></div></article>):<p className="knowledge-empty">Your saved shortcuts will appear here, with the exact command each one runs.</p>}</section>
      </>}
    </div></div>
  </dialog>;
}
