import React, { useState } from 'react';
import { Check, LoaderCircle, Plus, X } from 'lucide-react';
import type { AgentSession, VisualGoal, VisualRepository, WifRepo } from './types';
import { completionDefinitionChanged, completionProblem, workConflicts, WORK_STATUS as STATUS, type GoalDraft } from './work-records';

/* Intent: a founder resuming work needs the next action first and proof close by.
   Hierarchy: outcome, next action and unfinished checks lead; native details hold
   decisions and coordination. Palette/depth/surfaces: existing petrol ink, amber
   attention and inset paper fields, quiet receipt borders. System type at 11/12px,
   4px spacing and 16px groups keep this an extension of the working inspector. */
export function WorkRecordEditor({ draft, goals, repo, sessions, repository, saving, error, onChange, onSave, onCancel, externalGoals, externalRepos, onLoadExternalGoals }: { draft: GoalDraft; goals: VisualGoal[]; repo: WifRepo; sessions: AgentSession[]; repository: VisualRepository; saving: boolean; error: string; onChange: (draft: GoalDraft) => void; onSave: () => void; onCancel: () => void; externalGoals?: VisualGoal[]; externalRepos?: Array<{id: string; name: string}>; onLoadExternalGoals?: () => void }) {
  const patch = (update: Partial<GoalDraft>) => onChange({ ...draft, ...update });
  const descendants = new Set(draft.id ? [draft.id] : []);
  for (let i = 0; i < goals.length; i++) for (const goal of goals) if (goal.parentId && descendants.has(goal.parentId)) descendants.add(goal.id);
  const [confirmedDefinition, setConfirmedDefinition] = useState<string | null>(null);
  const previous = goals.find(goal => goal.id === draft.id);
  const definition = JSON.stringify([draft.id, draft.acceptanceCriteria, draft.checklist, draft.dependsOn, draft.crossRepoDependsOn, draft.scopePaths]);
  const changedDefinition = completionDefinitionChanged(draft, previous);
  const needsReconfirmation = changedDefinition && confirmedDefinition !== definition;
  const problem = needsReconfirmation ? 'This completed outcome changed. Reopen it for verification, or confirm that you verified the revised outcome.' : completionProblem(draft, [...goals, ...externalGoals ?? []]);
  const conflicts = workConflicts({ ...draft, id: draft.id ?? '', repoId: repo.id }, goals);
  const linkedSession = sessions.find(session => session.key === draft.sessionKey);
  const child = linkedSession?.children?.find(item => item.id === draft.agentId);
  const owner = sessions.find(session => session.key === draft.ownerSessionKey);
  const lines = (value: string) => value.split('\n');
  const branches = [...new Set([...repo.branches.map(branch => branch.name), ...repo.places.map(place => place.branch).filter((branch): branch is string => Boolean(branch)), ...(draft.branch ? [draft.branch] : [])])].sort();
  return <form className="vw-goal-editor" onSubmit={event => { event.preventDefault(); if (!problem) onSave(); }}><fieldset disabled={saving}><div className="vw-inspector-kicker">{draft.id ? 'Edit work' : draft.parentId ? 'New task' : 'New goal'}</div><label>What should happen?<input autoFocus required maxLength={240} value={draft.title} onChange={event => patch({ title: event.target.value })} placeholder="A concrete outcome…" /></label><label>Status<select value={draft.status} onChange={event => patch({ status: event.target.value as VisualGoal['status'] })}>{Object.entries(STATUS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Next action<textarea maxLength={2000} rows={3} value={draft.nextStep} onChange={event => patch({ nextStep: event.target.value })} placeholder="The next concrete step, including what is blocking it…" /></label>
    <div className="vw-record-checks"><div className="vw-record-label">Checklist <span>{draft.checklist.filter(item => item.done).length}/{draft.checklist.length}</span></div>{draft.checklist.map((item, index) => <div className="vw-check-edit" key={item.id}><input type="checkbox" aria-label={`Complete checklist item ${index + 1}`} checked={item.done} onChange={event => patch({ checklist: draft.checklist.map(row => row.id === item.id ? { ...row, done: event.target.checked } : row) })} /><input required aria-label={`Checklist item ${index + 1}`} maxLength={500} value={item.text} onChange={event => patch({ checklist: draft.checklist.map(row => row.id === item.id ? { ...row, text: event.target.value } : row) })} /><button type="button" className="vw-record-remove" aria-label={`Remove checklist item ${index + 1}`} onClick={() => patch({ checklist: draft.checklist.filter(row => row.id !== item.id) })}><X size={13} /></button></div>)}<button type="button" className="vw-button" disabled={draft.checklist.length >= 50} onClick={() => patch({ checklist: [...draft.checklist, { id: crypto.randomUUID(), text: '', done: false }] })}><Plus size={12} />Add check</button></div>
    <details><summary>Acceptance and verification <span>{draft.completion ? STATUS[draft.status] : 'What counts as done?'}</span></summary><label>Acceptance criteria<textarea rows={3} maxLength={4000} value={draft.acceptanceCriteria} onChange={event => patch({ acceptanceCriteria: event.target.value })} placeholder="The behavior or result that must be verified…" /></label><label>Completion evidence<select value={draft.completion?.kind ?? ''} onChange={event => patch({ completion: event.target.value ? { kind: event.target.value as 'reported' | 'confirmed', summary: draft.completion?.summary ?? '', reference: draft.completion?.reference ?? '' } : null })}><option value="">No completion claim</option><option value="reported">Reported complete · still needs verification</option><option value="confirmed">I have verified the outcome</option>{draft.completion?.kind === 'legacy' && <option value="legacy">Previously marked done · no verification recorded</option>}</select></label>{draft.completion && <><label>{draft.completion.kind === 'legacy' ? 'Historical completion note' : 'What was verified?'}<textarea readOnly={draft.completion.kind === 'legacy'} required rows={3} maxLength={2000} value={draft.completion.summary} onChange={event => patch({ completion: { ...draft.completion!, summary: event.target.value } })} /></label><label>Evidence reference<input readOnly={draft.completion.kind === 'legacy'} maxLength={1000} value={draft.completion.reference} onChange={event => patch({ completion: { ...draft.completion!, reference: event.target.value } })} placeholder="Test result, commit, artifact, or observation" /></label></>}<p className="vw-footnote">New completion requires a confirmed outcome, completed checks, and finished dependencies. Historical completion stays unchanged when you edit notes.</p></details>
    <details><summary>Settled findings <span>{draft.findings.length || 'Avoid repeating an investigation'}</span></summary>{draft.findings.map((item, index) => <div className="vw-record-entry" key={item.id}><label>Finding {index + 1}<textarea required rows={2} maxLength={1000} value={item.text} onChange={event => patch({ findings: draft.findings.map(row => row.id === item.id ? { ...row, text: event.target.value } : row) })} /></label><label>Evidence<textarea required rows={2} maxLength={1000} value={item.evidence} onChange={event => patch({ findings: draft.findings.map(row => row.id === item.id ? { ...row, evidence: event.target.value } : row) })} /></label><label>Revisit only when<input maxLength={500} value={item.revisitWhen} onChange={event => patch({ findings: draft.findings.map(row => row.id === item.id ? { ...row, revisitWhen: event.target.value } : row) })} placeholder="The condition that would change this conclusion" /></label><button type="button" className="vw-button" onClick={() => patch({ findings: draft.findings.filter(row => row.id !== item.id) })}>Remove finding</button></div>)}<button type="button" className="vw-button" disabled={draft.findings.length >= 40} onClick={() => patch({ findings: [...draft.findings, { id: crypto.randomUUID(), text: '', evidence: '', revisitWhen: '' }] })}><Plus size={12} />Add finding</button></details>
    <details><summary>Supporting evidence <span>{draft.evidence.length || 'References that travel with the work'}</span></summary>{draft.evidence.map((item, index) => <div className="vw-record-entry" key={item.id}><label>Evidence {index + 1}<textarea required rows={2} maxLength={1000} value={item.summary} onChange={event => patch({ evidence: draft.evidence.map(row => row.id === item.id ? { ...row, summary: event.target.value } : row) })} /></label><label>Reference<input maxLength={1000} value={item.reference} onChange={event => patch({ evidence: draft.evidence.map(row => row.id === item.id ? { ...row, reference: event.target.value } : row) })} /></label><button type="button" className="vw-button" onClick={() => patch({ evidence: draft.evidence.filter(row => row.id !== item.id) })}>Remove evidence</button></div>)}<button type="button" className="vw-button" disabled={draft.evidence.length >= 40} onClick={() => patch({ evidence: [...draft.evidence, { id: crypto.randomUUID(), summary: '', reference: '' }] })}><Plus size={12} />Add evidence</button></details>
    <details><summary>Ownership and parallel work <span>{draft.ownerSessionKey ? owner ? 'Assigned' : 'Owner unavailable' : 'Unassigned'}</span></summary><label>Responsible session<select value={draft.ownerSessionKey ?? ''} onChange={event => patch({ ownerSessionKey: event.target.value || null })}><option value="">Unassigned · explicitly release ownership</option>{sessions.map(session => <option key={session.key} value={session.key}>{session.appLabel} · {session.title}</option>)}{draft.ownerSessionKey && !owner && <option value={draft.ownerSessionKey}>Assigned session unavailable · needs continuation</option>}</select></label>{draft.ownerSessionKey && !owner && <p className="vw-record-warning">The assigned session is unavailable. Its ownership remains until you explicitly reassign or release it.</p>}<label>Files or folders in scope<textarea rows={3} value={draft.scopePaths.join('\n')} onChange={event => patch({ scopePaths: lines(event.target.value) })} placeholder={'One repository-relative path per line\nsrc/core/agent-sessions.mjs'} /></label><label>Shared decisions<textarea rows={2} value={draft.coordinationKeys.join('\n')} onChange={event => patch({ coordinationKeys: lines(event.target.value) })} placeholder={'One shared decision per line\nsession-lifecycle-contract'} /></label><div className="vw-record-label">Must run one at a time with</div><div className="vw-dependency-options">{goals.filter(goal => goal.id !== draft.id).map(goal => <label key={goal.id}><input type="checkbox" checked={draft.serialWith.includes(goal.id)} onChange={event => patch({ serialWith: event.target.checked ? [...draft.serialWith, goal.id] : draft.serialWith.filter(id => id !== goal.id) })} /><span>{goal.title}</span></label>)}</div>{conflicts.length > 0 && <div className="vw-record-warning"><strong>Coordinate before starting</strong>{conflicts.map(conflict => <p key={conflict.goal.id}>{conflict.goal.title}: {conflict.reasons.join('; ')}.</p>)}</div>}<p className="vw-footnote">Scopes and shared decisions flag likely conflicts. They are declarations, not proof that parallel edits are safe.</p></details>
    <label>Part of<select value={draft.parentId} onChange={event => patch({ parentId: event.target.value })}><option value="">A goal of its own</option>{goals.filter(goal => !descendants.has(goal.id)).map(goal => <option key={goal.id} value={goal.id}>{goal.title}</option>)}</select></label>
    <details open={draft.dependsOn.length > 0}><summary>Dependencies <span>{draft.dependsOn.length || ''}</span></summary><div className="vw-dependency-options">{goals.filter(goal => goal.id !== draft.id).map(goal => <label key={goal.id}><input type="checkbox" checked={draft.dependsOn.includes(goal.id)} onChange={event => patch({ dependsOn: event.target.checked ? [...draft.dependsOn, goal.id] : draft.dependsOn.filter(id => id !== goal.id) })} /><span>{goal.title}</span></label>)}{goals.filter(goal => goal.id !== draft.id).length === 0 && <p>No other goals to depend on yet.</p>}</div></details>
    {(onLoadExternalGoals || draft.crossRepoDependsOn.length > 0) && <details><summary>Dependencies in other projects <span>{draft.crossRepoDependsOn.length || 'Optional'}</span></summary><p className="vw-footnote">Choose a specific dependency. Only that reference appears in this project’s tree.</p>{onLoadExternalGoals && <button type="button" className="vw-button" onClick={onLoadExternalGoals}>{externalGoals ? 'Refresh projects' : 'Choose from other projects'}</button>}<div className="vw-dependency-options">{externalGoals?.map(goal => <label key={goal.id}><input type="checkbox" checked={draft.crossRepoDependsOn.some(ref => ref.goalId === goal.id && ref.repoId === goal.repoId)} onChange={event => patch({ crossRepoDependsOn: event.target.checked ? [...draft.crossRepoDependsOn, {repoId:goal.repoId,goalId:goal.id}] : draft.crossRepoDependsOn.filter(ref => !(ref.repoId === goal.repoId && ref.goalId === goal.id)) })} /><span>{externalRepos?.find(repo => repo.id === goal.repoId)?.name ?? 'Other project'} · {goal.title}</span></label>)}{draft.crossRepoDependsOn.filter(ref => !externalGoals?.some(goal => goal.id === ref.goalId && goal.repoId === ref.repoId)).map(ref => <label key={`${ref.repoId}:${ref.goalId}`}><input type="checkbox" checked onChange={() => patch({crossRepoDependsOn:draft.crossRepoDependsOn.filter(item => item !== ref)})} /><span>Saved external dependency · {ref.goalId}</span></label>)}</div></details>}
    <details className="vw-link-fields"><summary>Connect to work <span>optional</span></summary><p>Links are chosen by you.</p><label>Folder<select value={draft.placeId} onChange={event => patch({ placeId: event.target.value })}><option value="">No folder linked</option>{repo.places.map(place => <option key={place.id} value={place.id}>{place.label}</option>)}{draft.placeId && !repo.places.some(place => place.id === draft.placeId) && <option value={draft.placeId}>Previously linked folder (unavailable)</option>}</select></label><label>Branch<select value={draft.branch} onChange={event => patch({ branch: event.target.value })}><option value="">No branch linked</option>{branches.map(branch => <option key={branch}>{branch}</option>)}</select></label><label>Session<select value={draft.sessionKey} onChange={event => patch({ sessionKey: event.target.value, agentId: '' })}><option value="">No session linked</option>{sessions.map(session => <option key={session.key} value={session.key}>{session.appLabel} · {session.title}</option>)}{draft.sessionKey && !sessions.some(session => session.key === draft.sessionKey) && <option value={draft.sessionKey}>Previously linked session (unavailable)</option>}</select></label>{(Boolean(linkedSession?.children?.length) || Boolean(draft.agentId)) && <label>Delegated agent<select value={draft.agentId} onChange={event => patch({ agentId: event.target.value })}><option value="">Lead session</option>{linkedSession?.children?.map(item => <option key={item.id} value={item.id}>{item.label} · {item.endedAt ? 'finished responding' : item.activity}</option>)}{draft.agentId && !child && <option value={draft.agentId}>Previously linked agent (unavailable)</option>}</select></label>}<label>Component<select value={draft.component} onChange={event => patch({ component: event.target.value })}><option value="">No component linked</option>{repository.codebase.nodes.map(node => <option key={node.id} value={node.id}>{node.label}</option>)}{draft.component && !repository.codebase.nodes.some(node => node.id === draft.component) && <option value={draft.component}>{draft.component} (not in this map)</option>}</select></label></details>
    {changedDefinition && <label className="vw-reconfirm"><input type="checkbox" checked={confirmedDefinition === definition} onChange={event => setConfirmedDefinition(event.target.checked ? definition : null)} /><span>I verified the revised outcome, including its acceptance criteria, checklist, dependencies and scope.</span></label>}{problem && <p className="vw-record-warning">{problem}</p>}{draft.origin && <details><summary>Captured from session context</summary><p className="vw-footnote">{draft.origin.summary}</p><ul className="vw-record-origin">{draft.origin.evidence.map((item, index) => <li key={index}>{item}</li>)}</ul></details>}{error && <p role="alert" className="vw-inline-error">{error}</p>}<div className="vw-form-actions"><button className="vw-button primary" type="submit" disabled={saving || !draft.title.trim() || Boolean(problem)}>{saving ? <LoaderCircle className="vw-spin" size={14} /> : <Check size={14} />}Save {draft.parentId ? 'task' : 'goal'}</button><button className="vw-button" type="button" onClick={onCancel} disabled={saving}>Cancel</button></div><p className="vw-footnote">Status is explicit. Session activity never marks a goal done.</p></fieldset></form>;
}
