import React from 'react';
import { Check, CircleAlert } from 'lucide-react';
import type { AgentSession, VisualGoal } from './types';
import { workConflicts, WORK_STATUS } from './work-records';

/* Intent: resume a loose end without rereading a conversation. The next action
   leads in existing petrol ink; amber is reserved for coordination/verification.
   Inset paper, quiet receipt borders, system 11/13px type, 4px rhythm and native
   disclosure sections keep evidence nearby without overwhelming the work graph. */
const stamp = (value: string) => Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }) : 'Time unavailable';
const ownerText = (goal: VisualGoal, sessions: AgentSession[]) => {
  if (!goal.ownerSessionKey) return 'Unassigned';
  const owner = sessions.find(session => session.key === goal.ownerSessionKey);
  return owner ? `${owner.appLabel} · ${owner.title}${!owner.live ? ' · not running' : ''}` : 'Owner unavailable · needs continuation';
};
export function WorkRecordQueue({ goals, sessions, selected, onSelect }: { goals: VisualGoal[]; sessions: AgentSession[]; selected: string | null; onSelect: (goal: VisualGoal) => void }) {
  const open = goals.filter(goal => !['done', 'dismissed'].includes(goal.status));
  if (!open.length) return null;
  const row = (goal: VisualGoal) => <button type="button" className="vw-work-row" key={goal.id} aria-pressed={selected === goal.id} onClick={() => onSelect(goal)}><span className={`vw-state ${goal.status}`}><span />{WORK_STATUS[goal.status]}</span><strong>{goal.title}</strong><span className="vw-work-next">{goal.nextStep || 'No next action recorded'}</span><small>{goal.checklist?.length ? `${goal.checklist.filter(item => item.done).length}/${goal.checklist.length} checked · ` : ''}{ownerText(goal, sessions)}</small></button>;
  return <div className="vw-work-queue" aria-label="Open work and next actions">{open.slice(0, 5).map(row)}{open.length > 5 && <details><summary>{open.length - 5} more open {open.length - 5 === 1 ? 'goal' : 'goals'}</summary>{open.slice(5).map(row)}</details>}</div>;
}
export function WorkRecordInspector({ goal, goals, sessions, onSelect }: { goal: VisualGoal; goals: VisualGoal[]; sessions: AgentSession[]; onSelect: (goal: VisualGoal) => void }) {
  const conflicts = workConflicts(goal, goals);
  const associated = [...new Set([...(goal.sessionKeys ?? []), goal.links.sessionKey, goal.ownerSessionKey].filter((value): value is string => Boolean(value)))];
  return <>
    <section className="vw-inspector-section vw-record-next"><span className="vw-inspector-kicker">Next action</span><p>{goal.nextStep || (goal.status === 'done' ? 'Outcome recorded as complete.' : goal.status === 'dismissed' ? 'This work was dismissed.' : 'No next action recorded yet.')}</p>{goal.status === 'needs-verification' && <p className="vw-record-warning">Reported complete. Verify the acceptance criteria before marking done.</p>}<p className="vw-footnote">{ownerText(goal, sessions)}</p>{goal.ownerSessionKey && !sessions.some(session => session.key === goal.ownerSessionKey) && <p className="vw-footnote">Ownership is retained. Edit this goal to continue in another session or explicitly release it.</p>}</section>
    {goal.checklist?.length ? <section className="vw-inspector-section"><span className="vw-inspector-kicker">Checklist · {goal.checklist.filter(item => item.done).length}/{goal.checklist.length}</span><ul className="vw-record-checklist">{goal.checklist.map(item => <li className={item.done ? 'checked' : ''} key={item.id}><span aria-label={item.done ? 'Complete' : 'Incomplete'}>{item.done ? <Check size={12} /> : '○'}</span><span>{item.text}</span></li>)}</ul></section> : null}
    {goal.acceptanceCriteria && <section className="vw-inspector-section"><span className="vw-inspector-kicker">Acceptance criteria</span><p className="vw-preserve-lines">{goal.acceptanceCriteria}</p></section>}
    {conflicts.length > 0 && <section className="vw-inspector-section vw-record-conflicts"><span className="vw-inspector-kicker"><CircleAlert size={12} /> Coordinate before starting</span>{conflicts.map(conflict => <div key={conflict.goal.id}><button type="button" className="vw-inline-link" onClick={() => onSelect(conflict.goal)}>{conflict.goal.title}</button><ul>{conflict.reasons.map(reason => <li key={reason}>{reason}</li>)}</ul></div>)}<p className="vw-footnote">Based on declared scope and ownership, including unavailable owners.</p></section>}
    {goal.completion && <section className="vw-inspector-section"><span className="vw-inspector-kicker">{goal.completion.kind === 'confirmed' ? 'Confirmed outcome' : goal.completion.kind === 'legacy' ? 'Earlier completion record' : 'Completion report'}</span><p>{goal.completion.summary || 'No verification summary was recorded.'}</p>{goal.completion.reference && <p className="vw-record-reference">{goal.completion.reference}</p>}{goal.completion.kind === 'legacy' && <p className="vw-footnote">This goal predates verification records.</p>}</section>}
    {goal.findings?.length ? <section className="vw-inspector-section"><span className="vw-inspector-kicker">Settled findings</span>{goal.findings.map(finding => <div className="vw-record-finding" key={finding.id}><strong>{finding.text}</strong><p>{finding.evidence}</p><p className="vw-footnote">{finding.revisitWhen ? `Revisit when: ${finding.revisitWhen}` : 'No condition for revisiting has been recorded.'}</p></div>)}</section> : null}
    {goal.evidence?.length ? <details className="vw-record-details"><summary>Supporting evidence · {goal.evidence.length}</summary>{goal.evidence.map(item => <div className="vw-record-finding" key={item.id}><strong>{item.summary}</strong>{item.reference && <p className="vw-record-reference">{item.reference}</p>}</div>)}</details> : null}
    {(goal.scopePaths?.length || goal.coordinationKeys?.length || goal.serialWith?.length) ? <details className="vw-record-details"><summary>Declared scope and coordination</summary>{goal.scopePaths?.length ? <p>Scope: {goal.scopePaths.join(', ')}</p> : null}{goal.coordinationKeys?.length ? <p>Shared decisions: {goal.coordinationKeys.join(', ')}</p> : null}{goal.serialWith?.map(id => { const other = goals.find(item => item.id === id); return <p key={id}>Run one at a time with {other ? <button type="button" className="vw-inline-link" onClick={() => onSelect(other)}>{other.title}</button> : id}.</p>; })}</details> : null}
    {goal.origin && <details className="vw-record-details"><summary>Captured context · {stamp(goal.origin.capturedAt)}</summary><p>{goal.origin.summary}</p><ul>{goal.origin.evidence.map((item, index) => <li key={index}>{item}</li>)}</ul><p className="vw-footnote">Preserved when this suggested goal was saved.</p></details>}
    {associated.length > 0 && <details className="vw-record-details"><summary>Session history · {associated.length}</summary><ul>{associated.map(key => { const session = sessions.find(item => item.key === key); return <li key={key}>{session ? `${session.appLabel} · ${session.title}` : 'Session unavailable'}{key === goal.ownerSessionKey && ' · current owner'}<code className="vw-record-reference">{key}</code></li>; })}</ul><p className="vw-footnote">These associations remain when a session closes or leaves the session list.</p></details>}
    {goal.history?.length ? <details className="vw-record-details"><summary>Record history · revision {goal.revision ?? 1}</summary><ol>{[...goal.history].reverse().map((item, index) => <li key={`${item.at}-${index}`}><span>{stamp(item.at)} · {item.actor === 'agent' ? 'Agent update' : 'Your update'} · {WORK_STATUS[item.status]}</span>{item.nextStep && <p>{item.nextStep}</p>}{item.sessionKey && <code className="vw-record-reference">{item.sessionKey}</code>}</li>)}</ol></details> : null}
  </>;
}
